game.Chat.ChatModules:Destroy()
game.Chat.ClientChatModules:Destroy()
game.Chat.ChatLocalization:Destroy()
game.Chat.ChatServiceRunner:Destroy()
game.Chat.BubbleChat:Destroy()
game.Chat.ChatScript:Destroy()
game.ReplicatedStroge.DefaultChatSystemChatEvents:Destroy()
game.TextChatService.BubbleChatConfiguration:Destroy()
